### ISSUE TITLE
[BUG] 低版本macos不支持 css gap 导致 icon 错乱

### ISSUE THREAD

**Issue by binglww** [tiny-craft/tiny-rdm#245]
**Tiny RDM Version**
1.1.12

**OS Version**
macOS 11.2.3 intel
safari 14.0.3 (16610.4.3.1.7)

**Describe the bug**
1、主页右下角icon排版不对，测试下来是因为不支持gap [（Safari 14.1 Adds Support for Flexbox Gaps）](https://css-tricks.com/safari-14-1-adds-support-for-flexbox-gaps/)
2、Ribbon.vue组件的 icon-button 组件传参方式错了
![image](https://github.com/tiny-craft/tiny-rdm/assets/45476065/46d26dd4-6ae5-49af-9ebf-795c8d0740b9)
![image](https://github.com/tiny-craft/tiny-rdm/assets/45476065/00a5346a-c681-46f7-9c7a-3175cf89ead8)
![image](https://github.com/tiny-craft/tiny-rdm/assets/45476065/7b897eb9-5340-4d84-ad8a-ed6be67acfa4)
![image](https://github.com/tiny-craft/tiny-rdm/assets/45476065/e6fc6e31-eea4-4f21-a6e8-0b843bf25abc)

**Comment by tiny-craft** [comment]
@binglww 是的，昨天有人也是这个系统，我看到截图有问题了。

帮忙把底部样式
```css
    .nav-menu-item {
        align-items: center;
        padding: 10px 0 15px;
        gap: 20px;
        --wails-draggable: none;

        .nav-menu-button {
            margin-bottom: 6px;

            :hover {
                color: v-bind('themeVars.primaryColor');
            }
        }
    }
```

替换成
```css
    .nav-menu-item {
        align-items: center;
        padding: 10px 0 15px;
        --wails-draggable: none;

        button {
            margin: 10px 0;
        }
    }
```
看看，我这没有个版本的mac，没法看效果😂
